# Theory/Computation Problems

### Problem 1 (20 points) 
Show that the stationary point (zero gradient) of the function
$$
\begin{aligned}
    f=2x_{1}^{2} - 4x_1 x_2+ 1.5x^{2}_{2}+ x_2
\end{aligned}
$$
is a saddle (with indefinite Hessian). Find the directions of downslopes away from the saddle. Hint: Use Taylor's expansion at the saddle point. Find directions that reduce $f$.

### Problem 2 (50 points) 

* (10 points) Find the point in the plane $x_1+2x_2+3x_3=1$ in $\mathbb{R}^3$ that is nearest to the point $(-1,0,1)^T$. Is this a convex problem? Hint: Convert the problem into an unconstrained problem using $x_1+2x_2+3x_3=1$.

* (40 points) Implement the gradient descent and Newton's algorithm for solving the problem. Attach your codes along with a short summary including (1) the initial points tested, (2) corresponding solutions, (3) a log-linear convergence plot.

### Problem 3 (10 points) 
Let $f(x)$ and $g(x)$ be two convex functions defined on the convex set $\mathcal{X}$. 
* (5 points) Prove that $af(x)+bg(x)$ is convex for $a>0$ and $b>0$. 
* (5 points) In what conditions will $f(g(x))$ be convex?

### Problem 4 (bonus 10 points)
Show that $f({\bf x}_1) \geq f(\textbf{x}_0) + 
    \textbf{g}_{\textbf{x}_0}^T(\textbf{x}_1-\textbf{x}_0)$ for a convex function $f(\textbf{x}): \mathcal{X} \rightarrow \mathbb{R}$ and for $\textbf{x}_0$, $\textbf{x}_1 \in \mathcal{X}$. 

# Design Problems

### Problem 5 (20 points) 
Consider an illumination problem: There are $n$ lamps and $m$ mirrors fixed to the ground. The target reflection intensity level is $I_t$. The actual reflection intensity level on the $k$th mirror can be computed as $\textbf{a}_k^T \textbf{p}$, where $\textbf{a}_k$ is given by the distances between all lamps to the mirror, and $\textbf{p}:=[p_1,...,p_n]^T$ are the power output of the lamps. The objective is to keep the actual intensity levels as close to the target as possible by tuning the power output $\textbf{p}$.

* (5 points) Formulate this problem as an optimization problem. 
* (5 points) Is your problem convex?
* (5 points) If we require the overall power output of any of the $n$ lamps to be less than $p^*$, will the problem have a unique solution?
* (5 points) If we require no more than half of the lamps to be switched on, will the problem have a unique solution?

# Note

For this homework, you may want to attach sketches as means to explain your ideas. Here is how you can attach images.

![everly1](img/everly7.jpg)

In [21]:
import numpy as np
obj = lambda x: (10*x[0])**2+(5*x[1])**2-(14*x[0])-(8*x[1])+(12*x[0]*x[1])+5  
def grad(x):
    return (10*x[1])-8+(12*x[0]), (20*x[0])-14+(12*x[1])
eps = 1e-3  
x0 = [0.,0.]  
k = 0  
soln = [x0]
x = soln[k]
error = np.linalg.norm(grad(x))
a = 0.01  

# # Armijo line search
# def line_search(x):
#     a = 1.  # initialize step size
#     phi = lambda a, x: obj(x) - a*0.8*grad(x)**2  
#     while phi(a,x)<obj(x-a*grad(x)):  
#         a = 0.5*a
#     return a

while error >= eps:  
#     a = line_search(x)
    x = x - a*np.array(grad(x))
    soln.append(x)
    error = np.linalg.norm(grad(x))
    
soln 

<ipython-input-21-836cfa6b5e5a>:4: RuntimeWarning: overflow encountered in double_scalars
  return (10*x[1])-8+(12*x[0]), (20*x[0])-14+(12*x[1])
<ipython-input-21-836cfa6b5e5a>:4: RuntimeWarning: invalid value encountered in double_scalars
  return (10*x[1])-8+(12*x[0]), (20*x[0])-14+(12*x[1])


[[0.0, 0.0],
 array([0.08, 0.14]),
 array([0.1364, 0.2472]),
 array([0.175312, 0.330256]),
 array([0.20124896, 0.39556288]),
 array([0.2175428 , 0.44784554]),
 array([0.22665311, 0.49059552]),
 array([0.23039518, 0.52639343]),
 array([0.23010842, 0.55714719]),
 array([0.22678069, 0.58426784]),
 array([0.22114022, 0.60879956]),
 array([0.21372344, 0.63151557]),
 array([0.20492507, 0.65298901]),
 array([0.19503516, 0.67364532]),
 array([0.18426641, 0.69380085]),
 array([0.17277435, 0.71369146]),
 array([0.16067229, 0.73349362]),
 array([0.14804225, 0.75333993]),
 array([0.13494319, 0.77333069]),
 array([0.12141694, 0.79354237]),
 array([0.10749267, 0.81403389]),
 array([0.09319016, 0.83485129]),
 array([0.07852221, 0.85603111]),
 array([0.06349643, 0.87760293]),
 array([0.04811657, 0.89959129]),
 array([0.03238345, 0.92201702]),
 array([0.01629573, 0.94489829]),
 array([-1.49583153e-04,  9.68251350e-01]),
 array([-0.01695677,  0.9920911 ]),
 array([-0.03413107,  1.01643153]),
 array([-0.

In [20]:
obj = lambda x: (x - 1)**2  # note that this is 1D. In Prob 2 it should be 2D.
grad = lambda x: 2*(x - 1)  # this is not the correct gradient!
eps = 1e-3  # termination criterion
x0 = 0.  # initial guess
k = 0  # counter
soln = [x0]  # use an array to store the search steps
x = soln[k]  # start with the initial guess
error = abs(grad(x))  # compute the error. Note you will need to compute the norm for 2D grads, rather than the absolute value
# a = 0.01  # set a fixed step size to start with

# Armijo line search
def line_search(x):
    a = 1.  # initialize step size
    phi = lambda a, x: obj(x) - a*0.8*grad(x)**2  # define phi as a search criterion
    while phi(a,x)<obj(x-a*grad(x)):  # if f(x+a*d)>phi(a) then backtrack. d is the search direction
        a = 0.5*a
    return a

while error >= eps:  # keep searching while gradient norm is larger than eps
    a = line_search(x)
    x = x - a*grad(x)
    soln.append(x)
    error = abs(grad(x))
    
soln  # print the search trajectory

[0.0,
 0.25,
 0.4375,
 0.578125,
 0.68359375,
 0.7626953125,
 0.822021484375,
 0.86651611328125,
 0.8998870849609375,
 0.9249153137207031,
 0.9436864852905273,
 0.9577648639678955,
 0.9683236479759216,
 0.9762427359819412,
 0.9821820519864559,
 0.9866365389898419,
 0.9899774042423815,
 0.9924830531817861,
 0.9943622898863396,
 0.9957717174147547,
 0.996828788061066,
 0.9976215910457995,
 0.9982161932843496,
 0.9986621449632622,
 0.9989966087224467,
 0.999247456541835,
 0.9994355924063762,
 0.9995766943047821]

In [11]:
import numpy as np
obj = lambda x: (10*x[0])**2+(5*x[1])**2-(14*x[0])-(8*x[1])+(12*x[0]*x[1])+5  
def grad(x):
    return (10*x[1])-8+(12*x[0]), (20*x[0])-14+(12*x[1])
np.linalg.norm(grad((0,1)))

2.8284271247461903

In [8]:
trail = [(0.,0.),(2.,3.)]
trail[0]

(0.0, 0.0)

In [14]:
trail=[(1,1),(2,3)]
np.array(trail[1])-np.array(trail[0])

array([1, 2])