# Theory/Computation Problems

### Problem 1 (20 points) 
Show that the stationary point (zero gradient) of the function
$$
\begin{aligned}
    f=2x_{1}^{2} - 4x_1 x_2+ 1.5x^{2}_{2}+ x_2
\end{aligned}
$$
is a saddle (with indefinite Hessian). Find the directions of downslopes away from the saddle. Hint: Use Taylor's expansion at the saddle point. Find directions that reduce $f$.

### Problem 2 (50 points) 

* (10 points) Find the point in the plane $x_1+2x_2+3x_3=1$ in $\mathbb{R}^3$ that is nearest to the point $(-1,0,1)^T$. Is this a convex problem? Hint: Convert the problem into an unconstrained problem using $x_1+2x_2+3x_3=1$.

* (40 points) Implement the gradient descent and Newton's algorithm for solving the problem. Attach your codes along with a short summary including (1) the initial points tested, (2) corresponding solutions, (3) a log-linear convergence plot.

### Problem 3 (10 points) 
Let $f(x)$ and $g(x)$ be two convex functions defined on the convex set $\mathcal{X}$. 
* (5 points) Prove that $af(x)+bg(x)$ is convex for $a>0$ and $b>0$. 
* (5 points) In what conditions will $f(g(x))$ be convex?

### Problem 4 (bonus 10 points)
Show that $f({\bf x}_1) \geq f(\textbf{x}_0) + 
    \textbf{g}_{\textbf{x}_0}^T(\textbf{x}_1-\textbf{x}_0)$ for a convex function $f(\textbf{x}): \mathcal{X} \rightarrow \mathbb{R}$ and for $\textbf{x}_0$, $\textbf{x}_1 \in \mathcal{X}$. 

# Design Problems

### Problem 5 (20 points) 
Consider an illumination problem: There are $n$ lamps and $m$ mirrors fixed to the ground. The target reflection intensity level is $I_t$. The actual reflection intensity level on the $k$th mirror can be computed as $\textbf{a}_k^T \textbf{p}$, where $\textbf{a}_k$ is given by the distances between all lamps to the mirror, and $\textbf{p}:=[p_1,...,p_n]^T$ are the power output of the lamps. The objective is to keep the actual intensity levels as close to the target as possible by tuning the power output $\textbf{p}$.

* (5 points) Formulate this problem as an optimization problem. 
* (5 points) Is your problem convex?
* (5 points) If we require the overall power output of any of the $n$ lamps to be less than $p^*$, will the problem have a unique solution?
* (5 points) If we require no more than half of the lamps to be switched on, will the problem have a unique solution?

![IMG-0053](images/IMG-0053.jpg)

![IMG-0054](images/IMG-0054.jpg)

![IMG-0055](images/IMG-0055.jpg)

In [13]:
#for value of a =0.01
import numpy as np
obj = lambda x: 5*x[0]**2+10*x[1]**2+(12*x[0]*x[1])-8*x[0]-14*x[1]+5# note that this is 1D. In Prob 2 it should be 2D.
def grad(x):
     return (10*x[0]+12*x[1]-8), (20*x[1]-12*x[0]-14)
eps = 1e-3  # termination criterion  
x0= [0.,0.]  # initial guess
k = 0  # counter
soln = [x0]  # use an array to store the search steps    
x = soln[k]  # start with the initial guess
error = np.linalg.norm(grad(x))  # compute the error. Note you will need to compute the norm for 2D grads, rather than the absolute value
a = 0.01  # set a fixed step size to start with

# Armijo line search
def line_search(x):
    a = 1.  # initialize step size
    h=([[10,12],[12,20]])
    d=-np.linalg.inv(h)*grad(x)
    phi = lambda a, x: obj(x) - a*0.8*np.transpose(grad(x))*d  # define phi as a search criterion
    while phi(a,x)<obj(x-a*grad(x)):  # if f(x+a*d)>phi(a) then backtrack. d is the search direction
        a = 0.5*a
    return a

while error >= eps:  # keep searching while gradient norm is larger than eps
    #a = line_search(x)
    x = x - a*np.array(grad(x))
    soln.append(x)
    error = np.linalg.norm(grad(x))
    
soln  # print the search trajectory  


[[0.0, 0.0],
 array([0.08, 0.14]),
 array([0.1352, 0.2616]),
 array([0.170288, 0.365504]),
 array([0.18939872, 0.45283776]),
 array([0.19611832, 0.52499805]),
 array([0.19350672, 0.58353264]),
 array([0.18413213, 0.63004692]),
 array([0.17011329, 0.66613339]),
 array([0.15316595, 0.69332031]),
 array([0.13465092, 0.71303616]),
 array([0.11562149, 0.72658704]),
 array([0.09686889, 0.73514421]),
 array([0.0789647 , 0.73973963]),
 array([0.06229947, 0.74126747]),
 array([0.04711743, 0.74048991]),
 array([0.0335469 , 0.73804602]),
 array([0.02162668, 0.73446245]),
 array([0.01132852, 0.73016516]),
 array([0.00257585, 0.72549155]),
 array([-0.00474072,  0.72070234]),
 array([-0.01075093,  0.71599299]),
 array([-0.01559499,  0.71150428]),
 array([-0.01941601,  0.70733202]),
 array([-0.02235425,  0.7035357 ]),
 array([-0.02454311,  0.70014605]),
 array([-0.02610632,  0.69717167]),
 array([-0.02715629,  0.69460457]),
 array([-0.02779321,  0.6924249 ]),
 array([-0.02810488,  0.69060474]),
 arra

In [14]:
#Gradient Method
import numpy as np
obj = lambda x: 5*x[0]**2+10*x[1]**2+(12*x[0]*x[1])-8*x[0]-14*x[1]+5# note that this is 1D. In Prob 2 it should be 2D.
def grad(x):
     return np.array([10*x[0]+12*x[1]-8, 20*x[1]+12*x[0]-14])
eps = 1e-3  # termination criterion  
x0= [0.,0.]  # initial guess
k = 0  # counter
soln = [x0]  # use an array to store the search steps    
x = soln[k]  # start with the initial guess
error = np.linalg.norm(grad(x))  # compute the error. Note you will need to compute the norm for 2D grads, rather than the absolute value
#a = 0.01  # set a fixed step size to start with


# Armijo line search
def line_search(x):
    a = 1.  # initialize step size
    d=-grad(x)
    phi = lambda a, x: obj(x) + a*0.8*np.dot(grad(x),d)  # define phi as a search criterion
    while phi(a,x)<obj(x-a*grad(x)):  # if f(x+a*d)>phi(a) then backtrack. d is the search direction
        a = 0.5*a
    return a

while error >= eps:  # keep searching while gradient norm is larger than eps
    a = line_search(x)
    x = x - a*np.array(grad(x))
    soln.append(x)
    error = np.linalg.norm(grad(x))
    
soln  # print the search trajectory

[[0.0, 0.0],
 array([0.0625  , 0.109375]),
 array([0.10986328, 0.19580078]),
 array([0.14542389, 0.26428223]),
 array([0.17178619, 0.31872964]),
 array([0.19098449, 0.36219818]),
 array([0.20460775, 0.39707492]),
 array([0.21389699, 0.42522498]),
 array([0.2257459 , 0.47098649]),
 array([0.22716314, 0.50022586]),
 array([0.22287655, 0.52006219]),
 array([0.20820431, 0.54894461]),
 array([0.124532  , 0.61427662]),
 array([0.08599204, 0.62803184]),
 array([0.03645422, 0.67896418]),
 array([0.02045071, 0.67844123]),
 array([-0.02277453,  0.70166208]),
 array([-0.03478701,  0.71666537]),
 array([-0.05054416,  0.72192391]),
 array([-0.06039699,  0.73242714]),
 array([-0.08354146,  0.74195478]),
 array([-0.0856678 ,  0.74706109]),
 array([-0.09917469,  0.75791006]),
 array([-0.10562305,  0.7599035 ]),
 array([-0.10953627,  0.76424141]),
 array([-0.11897805,  0.76794228]),
 array([-0.11977577,  0.77009513]),
 array([-0.12519875,  0.77452096]),
 array([-0.12784025,  0.77526882]),
 array([-0.12

In [12]:
#Newton Method
import numpy as np
obj = lambda x: (2-2*x[0]-3*x[1])**2 + x[0]**2 +(x[1]-1)**2# note that this is 1D. In Prob 2 it should be 2D.
def grad(x):
     return np.array([10*x[0]+12*x[1]-8, 20*x[1]+12*x[0]-14])
h=([[10,12],[12,20]])
eps = 1e-3  # termination criterion  
x0= np.zeros((2),dtype=int)  # initial guess
k = 0  # counter
soln = [x0]  # use an array to store the search steps    
x = soln[k]  # start with the initial guess
error = np.linalg.norm(grad(x))  # compute the error. Note you will need to compute the norm for 2D grads, rather than the absolute value
a = 1  # set a fixed step size to start with

# Armijo line search
def line_search(x):
    a = 1.  # initialize step size
    d=-np.matmul(np.linalg.inv(h),grad(x))    
    phi = lambda a, x: obj(x) + a*0.8*np.dot(grad(x),d)  # define phi as a search criterion
    while phi(a,x)<obj(x+a*d):  # while phi(a,x)<obj(x-a*grad(x)): # if f(x+a*d)>phi(a) then backtrack. d is the search direction
        a = 0.5*a
    return a

while error >= eps:  # keep searching while gradient norm is larger than eps
    a = line_search(x)
    d=-np.matmul(np.linalg.inv(h),grad(x))
    x = x+a*d
    soln.append(x)
    error = np.linalg.norm(grad(x))
    
soln  # print the search trajectory

[array([0, 0]),
 array([-0.03571429,  0.19642857]),
 array([-0.0625 ,  0.34375]),
 array([-0.08258929,  0.45424107]),
 array([-0.09765625,  0.53710938]),
 array([-0.10895647,  0.5992606 ]),
 array([-0.11743164,  0.64587402]),
 array([-0.12378802,  0.68083409]),
 array([-0.1285553 ,  0.70705414]),
 array([-0.13213076,  0.72671918]),
 array([-0.13481236,  0.74146795]),
 array([-0.13682355,  0.75252954]),
 array([-0.13833195,  0.76082572]),
 array([-0.13946325,  0.76704786]),
 array([-0.14031172,  0.77171447]),
 array([-0.14094808,  0.77521442]),
 array([-0.14142534,  0.77783939]),
 array([-0.14178329,  0.77980811]),
 array([-0.14205176,  0.78128466]),
 array([-0.1422531 ,  0.78239206]),
 array([-0.14240411,  0.78322262]),
 array([-0.14251737,  0.78384554]),
 array([-0.14260231,  0.78431272]),
 array([-0.14266602,  0.78466311]),
 array([-0.1427138 ,  0.78492591]),
 array([-0.14274964,  0.785123  ]),
 array([-0.14277651,  0.78527082]),
 array([-0.14279667,  0.78538169]),
 array([-0.1428117

![IMG-0056](images/IMG-0056.jpg)

![IMG-0057](images/IMG-0057.jpg)

![IMG-0058](images/IMG-0058.jpg)

![IMG-0059](images/IMG-0059.jpg)

![IMG-0060](images/IMG-0060.jpg)